service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  getDataFunction:
    handler: index.getData
    events:
      - httpApi:
          path: /
          method: GET
   
